🛠️
OPPO9008/galgamer pull request #87
Opened 2022-01-22 12:30 UTC by codehz

顺便简化了一下代码

2022-01-24 12:44 UTC, Yamabuki-bakery approved these changes
images

2022-01-24 12:44 UTC, Yamabuki-bakery approved these changes
依賴

2022-01-24 12:45 UTC, Yamabuki-bakery requested changes
沒有註釋，建議槍斃

2022-01-24 13:08 UTC, Yamabuki-bakery commented on source/_posts/森灵之心.md
> +作为《塔菈秀》的死忠粉以及镇长的女儿，摩根是个……与众不同的人。当她不经营她的小而空的古董店时，她就会消失在森林里，一连好几天。再加上她对传统社会制度的抵制，摩根在小镇的名声可谓臭名昭著。
《塔菈秀》和 艾森菲尔德 是什么？
这一句读起来感觉有点混乱

2022-01-24 13:08 UTC, Yamabuki-bakery commented on source/_posts/森灵之心.md
> +
我们最喜欢的盗版游戏环节...？

2022-01-24 13:08 UTC, Yamabuki-bakery commented on source/_posts/森灵之心.md
> +
> LGBTQ+ 警告，不能接受跨性别的建议放弃。

别随便放弃，请问这个游戏为什么好玩到能让你克服 LGBTQ？

> 游戏画面方面，虽然本作是Rosuuri参与的第一部18+视觉小说，立绘和CG却异常精美，虽然是来自美国，但是画风方面也有日系的特点。

作为 Rosuuri （公司名？人名？）的第一部 R-18 视觉小说，立绘和 CG 是.....
融合了美国和日系的画风是什么特点？

> 剧情发展顺畅，没有强行拖时间的环节，几乎每个情节都安排得恰到好处。

剧情安排精妙，每一个环节都承上启下，恰到好处....（是否有悬疑？是否有伏笔？情节的安排体现了作者怎样的构思？）

> 喜欢百合且能接受变性设定的可以来玩玩

喜欢百合且能接受变性设定（喜欢鬼片，喜欢悬疑，喜欢 xx...）的建议玩爆

2022-01-24 13:10 UTC, codehz commented on source/_posts/森灵之心.md
> +
(太容易搜索了，，随便拉谷歌就是一堆

2022-01-24 13:10 UTC, codehz commented on source/_posts/森灵之心.md
> +
但是显然不能给人家打广告）

2022-01-24 13:12 UTC, Yamabuki-bakery commented on source/_posts/森灵之心.md
> +
> (太容易搜索了，，随便拉谷歌就是一堆

把这句话打上去

2022-01-24 13:13 UTC, codehz commented on source/_posts/森灵之心.md
> +  - - Studio Élan
这玩意自动格式化

2022-01-24 13:15 UTC, codehz commented on source/_posts/森灵之心.md
> +{% ruby 麦荻 Maddie %}·{% ruby 雷恩斯 Raines %}是她最好的朋友{% ruby 塔菈 Tara %}的流行超自然视频频道担任经理和编辑。她们两个一起调查了几乎所有的神秘和鬼故事，但从未发现任何无法解释的超自然现象。这次她们的粉丝介绍了一个有着巨型森林精灵传说的偏远的德国村庄，麦荻期待着能在其中发现真正的超自然现象。
大洋彼岸 = 美国到德国
村子 = 艾森菲尔德村，待会改改

2022-01-24 13:19 UTC, codehz commented on source/_posts/森灵之心.md
> +{% ruby 麦荻 Maddie %}·{% ruby 雷恩斯 Raines %}是她最好的朋友{% ruby 塔菈 Tara %}的流行超自然视频频道担任经理和编辑。她们两个一起调查了几乎所有的神秘和鬼故事，但从未发现任何无法解释的超自然现象。这次她们的粉丝介绍了一个有着巨型森林精灵传说的偏远的德国村庄，麦荻期待着能在其中发现真正的超自然现象。
为什么要退出节目这个其实有点涉嫌剧透了，游戏开场也是直接抛出这个，剧情中间才给解释）

2022-01-25 03:06 UTC, Yamabuki-bakery approved these changes
ok

2022-01-25 03:14 UTC, codehz commented
可以合并了

2022-01-25 05:36 UTC, merged